### ISSUE TITLE
Why dependency on gtk4-wayland instead of gtk4?

### ISSUE THREAD

**Issue by Maxime2** [jcupitt/vipsdisp#10]
https://github.com/jcupitt/vipsdisp/blob/31d2b94ec42728521cf0b0dcfeda7ddfa620c7e2/meson.build#L41

Why dependency set to be on gtk4-wayland? GTK4 can be built without Wayland backend. 
I have replaced gtk4-wayland with gtk4 and was able to build vipsdisp successfully and run it under Broadway backend.

**Comment by jcupitt** [comment]
Hi @Maxime2,

I don't remember why I used `gtk4-wayland`. I think I was trying to make sure I had the GPU-backed backend for testing. Sure, let's change it to plain gtk4.

I've not tried it with broadway -- that's interesting. What was performance like?

**Comment by Maxime2** [comment]
Hello, @jcupitt ,

I have not tested performance. I have tried vipsdisp because it supports GTK4 and we need an image viewer able to work with GTK4 Broadway. The vipsdisp just works and displays ordinary images (not overly big) instantly. Thank you!

**Comment by jcupitt** [comment]
OK, switched to plain gtk4. Thanks for the report!
