### ISSUE TITLE
Add multiple file support

### ISSUE THREAD

**Issue by srhardie** [jcupitt/vipsdisp#28]
RFE - Are you able to please add keyboard shortcuts for moving forward/backwards through multiple image files in a directory. Currently if there are multiple images in the same directory, from Nautilus file browser I open the first image file for viewing. Then to view the second image, I need to use the 'Replace Image...' dialog or go back to Nautilus and double-click on the next file. This is slow for moving through dozens or hundreds of image files in a directory. Perhaps as mentioned in the vipsdisp TODO list, something like Shift-left and Shift-right? Similar to Gnome Image Viewer (EOG) using left/right arrow keys to move through multiple image files.

Fedora 38, vipsdisp 2.6.3 as a flatpak from flathub.org

**Comment by jcupitt** [comment]
Hello @srhardie, yes this has to be the most requested feature.

I've been making this thing as a new image view window for nip2:

https://github.com/libvips/nip2

That thing needs updating for gtk4, and image display is probably the bit that's changed most since gtk2. Since this will be a widget in a spreadsheet, it won't need multiple image support.

... having said that, I agree that as a lightweight standalone viewer, it would be useful for `vipsdisp`.

**Comment by jcupitt** [comment]
... I decided this feature was more interesting than anything else I had planned today, so I hacked in basic support. There are a few things to look at still:

- it uses alt-left and right
- if you run `vipsdisp a/b/c.xx`, then left/right cycles though all files in directory `a/b`
- if you run `vipsdisp a.x b.y`, then it cycles between those files
- need to add multi-file drag and drop, and multi-file copy and paste
- we could improve caching of recently opened files
- could improve killing of background loads of abandoned images

**Comment by jcupitt** [comment]
>  to view the second image, I need to use the 'Replace Image...' dialog or go back to Nautilus and double-click on the next file

git master vipsdisp supports drag and drop and copy paste, so you can just drag files from nautilus. Proper multi-file support is better, of course.

**Comment by srhardie** [comment]
Thanks! This will be immediately useful in a large image processing project.

I compiled from master and tested it out. Cycling through image files using alt-left/right works great.

Looking forward to an updated flatpak on flathub when you can.
