### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by haesleinhuepf** [jcupitt/vipsdisp#29]
Hi @jcupitt et al,

that's a fantastic tool, thanks for sharing! I was just wondering under which conditions one could reuse the tools and code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jcupitt** [comment]
Hey @haesleinhuepf, thanks for your kind words.

it's MIT (check the About dialog), did I forget to put a licence file in? I'll fix it.

**Comment by jcupitt** [comment]
... though of course the binaries on the "releases" page will have a different licence.

**Comment by haesleinhuepf** [comment]
Awesome, thanks for the rapid response!
