### ISSUE TITLE
2 issues and 1 suggestion with latest version 3.0.4 on windows

### ISSUE THREAD

**Issue by euzada** [jcupitt/vipsdisp#30]
Vipsdisp version : 3.0.4
Windows 10, 64bit

1- in touch screen, pinch and zoom with fingers is not working. move the image with 1 finger is working. It was working on the previous version 2.6

2- go to Next/Previous image is only working on the to menu bar (close to Open), it does not work on the menu (or right click menu). This is a problem for Full screen mode.

3- Suggestion: Add a Sync option if we are opening multiple similar images and we zoom on first image and we go to next image, if the "Sync" option is selected, the second image will be zoomed to the same location. The coordinates (X and Y) and zoom level will be preserved from image to image.

**Comment by jcupitt** [comment]
Hi @euzada,

Thanks for testing and feedback. After a while I can't see what's wrong any more :( so someone else's eyes are really useful.

1. I had to remove this code for now, unfortunately, it wasn't fully implemented and was messing up two finger touchpad scrolling. I think I'd need a touch screen before I could test this properly.

2. It's working for me. Do you mean the `< >` in the top line of the right-click menu? They are for next/prev page (not image) -- you need the "next image" menu item a little way down. 

   Now I look again, you're right that it's confusing to use `< >` both for next/prev page and next/prev image, perhaps page next/prev should be different? Maybe `|< >|` for next/prev image, and `< >` for next/prev page?

4. I agree, I agonised about this issue. 

   An earlier version did keep the view settings on next/prev image, but I found it confusing. I kept flipping to a new image and being unsure if I was seeing the whole thing or a detail.

   My idea was to do this backwards, so view settings are preserved if you return to an old image, but always reset on new images. It seemed (to me) to have most of the advantages of "preserve", but without needing any extra controls.

**Comment by euzada** [comment]
Thank you @jcupitt for your quick response.

1- I understand how hard to test it without touch screen. I use it to inspect a large stitching image after the stitching is completed. The fact that touch screen can zoom really fast, I found it practical. 

2- Yes, I got confused between the icons of page and image. Your suggestion is really helpful if they have 2 different icon shape. I moved the mouse on the top of the icon, hoping to tell me the icon function, but didn't. If when we move the cursor on the top of the icon and we see a description like "Next Image" or "Next page" will also be helpful. 
Testing again, I found that if I have another file, like txt or exe in the same folder of the image, the "Next image" will try to open the txt or exe file and say cannot open it. Will also be a good idea to filter only the image extensions that the vips support and ignore the remaining extensions.

3- The "Sync" idea, I got it from a GDS design software called "Klayout" that allow to open multiple GDS file (in different tab), but if the "Sync" is activated, when we zoom in one file, the second tab will zoom directly to the same location and same zoom level. It is an easy way to compare 2 files (here 2 images).

**Comment by jcupitt** [comment]
2. I swapped the menu around so the bar at the top is prev-image / next-image, and the menu items are prev-page / next-page. They should have a tooltip on hover, maybe something is messed up in your gtk4 install? Or you have a very old version?

3. I'm vague about the UI for this. Are you imagining a "lock view settings" toggle in the right-click menu? I think preserving settings on prev-image (what it does now) is probably simpler and less confusing. 

4. It's there for me. What gtk4 version are you using? Or are you using one of the precompiled versions of vipsdisp?

5. Yes, I wondered about skipping unknown files. It's hard to do well, unfortunately, with quite a few annoying edge cases and performance issues. I added a note to the to-do list in the  README.

**Comment by jcupitt** [comment]
Ah sorry, you said the windows build. No tooltips and a messed up fullscreen icon are probably gtk4 bugs.

**Comment by jcupitt** [comment]
... I tried revising the menu and top bar again. It might help the win build too.

**Comment by jcupitt** [comment]
I added a "Preserve view settings on new image" toggle to the display control bar menu (next to the ICC profile toggle) and it seems to mostly work, though it's a bit confusing. It'll be in the next version.

Thanks for the idea!
