### ISSUE TITLE
Pixelation when zoomed in

### ISSUE THREAD

**Issue by prasadbandodkar** [jcupitt/vipsdisp#31]
How can i see the individual pixels when I zoom in? I always see a smooth image even when I zoom in fully. Is there a change to make in the imagedisplay object or does it have to with gdktexture in the tile object or is it in the settings in libvips? Could you please help with that? Thanks!

**Comment by jcupitt** [comment]
Hi @prasadbandodkar, it depends on your gtk version. Nearest neighbour upscaling was added in gtk4.10, so if you build with that, you'll get chunky pixels.

The flatpak build was with 4.11 (I think?) so you can use that and get chunky pixels without touching your gtk installation.
