### ISSUE TITLE
Tests of vipsdisp WSI viewer with various DICOM WSI from Imaging Data Commons

### ISSUE THREAD

**Issue by DanielaSchacherer** [jcupitt/vipsdisp#35]
Hi! I am working on the [Imaging Data Commons (IDC) project](https://learn.canceridc.dev/) together with @fedorov and @dclunie. We came across your vipsdisp viewer and tested it with some WSI that we have available. They are all in DICOM format and could be displayed. However, in contrast to many other WSI formats, each DICOM file represents only one level of the WSI pyramid. The Vipsdisp viewer doesn't seem to be able to recognize other matching DICOM files in the same location. 
We thought that this could be a valuable improvement. 

Best regards, 
Daniela

**Comment by jcupitt** [comment]
Hi @DanielaSchacherer, thanks for having a look at vipsdisp.

It should pick up the whole pyramid. For example, I see:

![image](https://github.com/user-attachments/assets/4a29873a-4a6b-4f6b-b323-62c6ac3c15c8)

As you can see, I ran the program on `0000002.dcm`, a 30kb level in that pyramid, but the viewer is displaying the full 50k x 90k pixel image. That's using the flatpak build of vipsdips, together with one of the public 3DHistech scans.

https://flathub.org/apps/org.libvips.vipsdisp

If you look at the image properties (alt-enter) you can see the number of pyramid layers it detected:

![image](https://github.com/user-attachments/assets/c1be2f22-632a-4cc2-aa08-4becfef9275f)

It has all the DICOM and openslide image metadata in there (it's rather indigestible, but you can filter the list with the search bar at the top).

**Comment by jcupitt** [comment]
You probably found it, but just in case, vipsdisp supports colour management of DICOM slides too. Turn on the display control bar and there's a tickbox in the menu:

![image](https://github.com/user-attachments/assets/74501d1c-31cc-4083-ae96-db409deef677)

It makes a big difference for some vendors.

**Comment by jcupitt** [comment]
Sorry, I keep thinking of things. Did you find the zooming controls? 

- use the mousewheel for a quick zoom
- press the number keys to jump to that zoom level (ie. pyramid level)
- press 0 to zoom out to fit the window
- press eg. ctrl-2 for a 50% zoom
- press + and - to step in and out a small amount
- hold i and o to smoothly zoom in and out on the mouse pointer
- there are also zoom controls in the View menu

**Comment by jcupitt** [comment]
Ahem I think I have it, do you mean it's not displaying the label image?

You're right, that would be a useful improvement, there's a note about it at the end of the TODO section in the README:

https://github.com/jcupitt/vipsdisp/blob/master/README.md#todo

It would need some changes to libvips and I've not decided quite how to handle it yet.

**Comment by DanielaSchacherer** [comment]
Hi @jcupitt, sorry that it took me some time to answer and thank you very much for your reply! 
I wasn't referring to the label image (yet, this would also be nice to have :)), but indeed to the different levels. After some debugging, I think that the problem was most likely related to some installation issue on my computer. I tried again in another computing environment and all levels were detected as you showed above.

**Comment by jcupitt** [comment]
Ah OK -- I'm glad it's working now.
