### ISSUE TITLE
Bug in opening large pictures (jpg)

### ISSUE THREAD

**Issue by Korokoro321** [jcupitt/vipsdisp#36]
hello, first thank you for developing such an amazing and easy to use tool, i found a bug when i try to open a picture that is larger then about 110 mb i get a "wbuffer-write: write failed" and "system error: No space left on the device", even tho that doesn't happen with nip3, my os is nobara and  im using vpdisp flatpak version

P.S: yes i have enough space be it ram or on the hard disk

**Comment by jcupitt** [comment]
vipsdisp is the image display window for nip4:

https://github.com/jcupitt/nip4

Though it's not done yet. There's a video showing off some of the new UI.

**Comment by Korokoro321** [comment]
thank you it worked like a charm, ill look up for nip4 in the future
