### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by teohhanhui** [jcupitt/vipsdisp#4]
This will be very promising (I love libvips!) to be used as a replacement for Eye of GNOME and gThumb (not available as flatpak).

**Comment by jcupitt** [comment]
Hi, I agree, a flatpak for this thing would be very useful.

**Comment by jcupitt** [comment]
I made a flatpak manifest: 

https://github.com/jcupitt/vipsdisp/blob/master/org.libvips.vipsdisp.json

It seems to work OK, though it'll need some work before flathub will accept it (desktop file, appdata, etc.). The README has some notes.

If anyone would like to get it into flathub, that would be great!

**Comment by teohhanhui** [comment]
> It'll build libvips without HEIC, AVIF, libgsf, JXL, OpenEXR OpenJPEG, poppler, openslide, matio, cfitsio, libimagequant, NIfTI, FITS etc. as they are not included in the SDK we use.

That's a major caveat. Haha... Typically a Flatpak app would build (in the manifest) and bundle the dependencies that it needs.

**Comment by jcupitt** [comment]
... I added JXL, it was pretty easy. More welcome, of course.

**Comment by jcupitt** [comment]
... I did the others, it all seems to work.

**Comment by jcupitt** [comment]
Submitted to flathub here: https://github.com/flathub/flathub/pull/2536
