### ISSUE TITLE
JPEG XL Support: Does not support container format.

### ISSUE THREAD

**Issue by Fraetor** [jcupitt/vipsdisp#5]
This viewer does not open JXL files that have a container, instead returning the error `VipsForeignLoad: source is not a known format`.

It does work for images with the container removed, or which where created without the container (which is the default for encoding jxl images from pixels.)

Here is a working example: (Remove .txt extension, its only there to allow GitHub upload)
[no-container.jxl.txt](https://github.com/jcupitt/vipsdisp/files/7262748/no-container.jxl.txt)
Here is a non-working example:
[container.jxl.txt](https://github.com/jcupitt/vipsdisp/files/7262750/container.jxl.txt)

**Comment by jcupitt** [comment]
Oh hey, thanks @Fraetor. I'll have a look.

**Comment by jcupitt** [comment]
OK, fixed in libvips master, thank you for pointing out this dumb thing.
